Repository hellosign/hellosign-openapi, pull requests merged in 2022-11, with the labels that each got.

#117 Signature Request Expiration Date SDK + Doc changes
  openapi-raw.yaml
  openapi-sdk.yaml
  openapi.yaml
  translations/en.yaml
Labels: hold, H22SP20

#130 split file download to different endpoints
  examples/SignatureRequestFilesAsDataUri.cs
  examples/SignatureRequestFilesAsDataUri.java
  examples/SignatureRequestFilesAsDataUri.js
  examples/SignatureRequestFilesAsDataUri.php
  examples/SignatureRequestFilesAsDataUri.py
  examples/SignatureRequestFilesAsDataUri.rb
  examples/SignatureRequestFilesAsDataUri.ts
  examples/TemplateFilesAsDataUri.cs
  examples/TemplateFilesAsDataUri.java
  examples/TemplateFilesAsDataUri.js
  examples/TemplateFilesAsDataUri.php
  examples/TemplateFilesAsDataUri.py
  examples/TemplateFilesAsDataUri.rb
  examples/TemplateFilesAsDataUri.ts
  openapi-raw.yaml
  openapi-sdk.yaml
  openapi.yaml
  translations/en.yaml
Labels: H22SP21

#134 Updated ApiAppGet NET example
  examples/ApiAppGet.cs
Labels: hold

#144 Adding total_templates to AccountQuota
  openapi-raw.yaml
  openapi-sdk.yaml
  openapi.yaml
  sdks/dotnet/docs/AccountResponseQuotas.md
  sdks/dotnet/src/HelloSign/Model/AccountResponseQuotas.cs
  sdks/java/docs/AccountResponseQuotas.md
  sdks/java/src/main/java/com/hellosign/openapi/model/AccountResponseQuotas.java
  sdks/node/dist/api.js
  sdks/node/docs/model/AccountResponseQuotas.md
  sdks/node/model/accountResponseQuotas.ts
  sdks/node/types/model/accountResponseQuotas.d.ts
  sdks/php/docs/Model/AccountResponseQuotas.md
  sdks/php/src/Model/AccountResponseQuotas.php
  sdks/python/docs/AccountResponseQuotas.md
  sdks/python/hellosign_sdk/model/account_response_quotas.py
  sdks/ruby/docs/AccountResponseQuotas.md
  sdks/ruby/lib/hellosign-ruby-sdk/models/account_response_quotas.rb
  translations/en.yaml
Labels: release fix
